name: dependent jobs

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Building application
        run: echo "Building application..."
      - name: Simulate build
        run: sleep 3

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Running tests
        run: echo "Running tests..."
      - name: Simulate testing
        run: sleep 3

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Deploying application
        run: echo "Deploying application..."
      - name: Simulate deployment
        run: sleep 3
