name: dependent jobs

on:
  push:
    branches:
      - main

jobs:
  job_on_ubuntu:
    runs-on: ubuntu-latest
    steps:
      - run: date

  job_on_windows:
    name: A windows job
    runs-on: windows-latest
    steps:
      - name: First step in windows job
        run: date

  job_on_macos:
    needs: [job_on_ubuntu, job_on_windows]
    runs-on: macos-latest
    name: A job that runs on Mac after first two jobs
    steps:
      - run: pwd
      - name: new step
        run: ls
      - name: third step
        run: env

  Final_job:
    needs: job_on_macos
    runs-on: ubuntu-latest
    name: A Final job
    steps:
      - run: echo Hello World!
