name: dependent jobs

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Building application
        run: |
          echo "Building application..."
          sleep 3

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Running tests
        run: |
          echo "Running tests..."
          sleep 3

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploying application
        run: |
          echo "Deploying application..."
          sleep 3
