name: multi-platform

on:
  pull_request:
    branches:
      - main

jobs:
  ubuntu-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Print OS information
        run: uname -a
      - name: Create and display file
        run: |
          echo "Hello from Ubuntu" > test.txt
          cat test.txt

  windows-job:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Print OS information
        run: systeminfo | findstr /B /C:"OS Name"
      - name: Create and display file
        run: |
          echo Hello from Windows > test.txt
          type test.txt

  macos-job:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Print OS information
        run: uname -a
      - name: Create and display file
        run: |
          echo "Hello from macOS" > test.txt
          cat test.txt
