name: Workflow 2 - Multi-Platform Testing

on:
  pull_request:
    branches: [ main ]

jobs:
  ubuntu-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Print OS Info
        run: uname -a
      - name: Create and Display File
        run: echo "Welcome to Ubuntu!" > info.txt | cat info.txt

  windows-job:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Print OS Info
        run: systeminfo
      - name: Create and Display File
        run: echo "Welcome to Windows!" > info.txt && type info.txt

  macos-job:
    runs-on: macos-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Print OS Info
        run: uname -a
      - name: Create and Display File
        run: echo "Welcome to macOS!" > info.txt && cat info.txt
